# Exercici 1

- 
Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carregaâ€™l a un pandas Dataframe.

In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



delayed_f = pd.read_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights.csv") 
delayed_f[:50] #I've chosen to only visualize the first 50 rows because the entire datafram was too heavy

,Index,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
10,17,2008,1,3,4,754.0,745,940.0,955,WN,...,5.0,16.0,0,N,0,NaN,NaN,NaN,NaN,NaN
11,18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,...,4.0,9.0,0,N,0,0.0,0.0,0.0,0.0,16.0
12,19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,...,2.0,5.0,0,N,0,12.0,0.0,0.0,0.0,25.0
13,21,2008,1,3,4,1657.0,1625,1754.0,1735,WN,...,5.0,5.0,0,N,0,7.0,0.0,0.0,0.0,12.0
14,22,2008,1,3,4,1900.0,1840,1956.0,1950,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
15,23,2008,1,3,4,1039.0,1030,1133.0,1140,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
16,25,2008,1,3,4,1520.0,1455,1619.0,1605,WN,...,2.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
17,26,2008,1,3,4,1422.0,1255,1657.0,1610,WN,...,6.0,6.0,0,N,0,40.0,0.0,0.0,0.0,7.0
18,27,2008,1,3,4,1954.0,1925,2239.0,2235,WN,...,3.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
19,30,2008,1,3,4,2107.0,1945,2334.0,2230,WN,...,6.0,7.0,0,N,0,5.0,0.0,0.0,0.0,59.0
20,33,2008,1,3,4,1312.0,1300,1546.0,1550,WN,...,7.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
21,34,2008,1,3,4,1449.0,1430,1715.0,1720,WN,...,6.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
22,35,2008,1,3,4,1634.0,1555,1859.0,1845,WN,...,5.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
23,37,2008,1,3,4,1812.0,1650,1927.0,1815,WN,...,6.0,11.0,0,N,0,3.0,0.0,0.0,0.0,69.0
24,38,2008,1,3,4,1127.0,1105,1235.0,1230,WN,...,9.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
25,39,2008,1,3,4,1424.0,1355,1531.0,1520,WN,...,8.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
26,40,2008,1,3,4,1326.0,1230,1559.0,1530,WN,...,5.0,5.0,0,N,0,0.0,0.0,0.0,0.0,29.0
27,41,2008,1,3,4,1749.0,1725,2019.0,2030,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
28,42,2008,1,3,4,726.0,720,958.0,1020,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
29,43,2008,1,3,4,646.0,640,929.0,955,WN,...,3.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
30,44,2008,1,3,4,1153.0,1140,1428.0,1440,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
31,45,2008,1,3,4,1528.0,1510,1802.0,1810,WN,...,4.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
32,48,2008,1,3,4,1450.0,1435,1806.0,1745,WN,...,7.0,8.0,0,N,0,0.0,0.0,6.0,0.0,15.0
33,49,2008,1,3,4,2245.0,1730,2354.0,1850,WN,...,3.0,7.0,0,N,0,282.0,0.0,0.0,0.0,22.0
34,52,2008,1,3,4,2025.0,1940,2135.0,2100,WN,...,3.0,7.0,0,N,0,26.0,0.0,0.0,0.0,9.0
35,53,2008,1,3,4,1038.0,945,1314.0,1225,WN,...,8.0,7.0,0,N,0,7.0,0.0,0.0,0.0,42.0
36,54,2008,1,3,4,1900.0,1850,2123.0,2045,WN,...,40.0,6.0,0,N,0,1.0,0.0,28.0,0.0,9.0
37,56,2008,1,3,4,948.0,925,959.0,940,WN,...,3.0,9.0,0,N,0,0.0,0.0,0.0,0.0,19.0
38,57,2008,1,3,4,646.0,620,725.0,655,WN,...,6.0,16.0,0,N,0,26.0,0.0,4.0,0.0,0.0
39,58,2008,1,3,4,1110.0,1040,1136.0,1110,WN,...,5.0,9.0,0,N,0,0.0,0.0,0.0,10.0,16.0
40,64,2008,1,3,4,2139.0,2130,2244.0,2240,WN,...,3.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
41,69,2008,1,3,4,1738.0,1730,1841.0,1840,WN,...,6.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
42,70,2008,1,3,4,1813.0,1735,1936.0,1905,WN,...,6.0,12.0,0,N,0,11.0,0.0,0.0,0.0,20.0
43,71,2008,1,3,4,802.0,750,1001.0,955,WN,...,7.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
44,74,2008,1,3,4,1734.0,1650,1941.0,1905,WN,...,4.0,10.0,0,N,0,3.0,0.0,0.0,0.0,33.0
45,75,2008,1,3,4,712.0,700,926.0,915,WN,...,5.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
46,76,2008,1,3,4,1318.0,1310,1410.0,1400,WN,...,4.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
47,77,2008,1,3,4,958.0,900,1052.0,950,WN,...,4.0,14.0,0,N,0,0.0,0.0,4.0,0.0,58.0
48,78,2008,1,3,4,1859.0,1850,1950.0,1945,WN,...,4.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
49,79,2008,1,3,4,1538.0,1445,1753.0,1710,WN,...,4.0,11.0,0,N,0,15.0,0.0,0.0,0.0,28.0

- Explora les dades que contÃ©, i quedaâ€™t Ãºnicament amb les columnes que consideris rellevants.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

delayed_f = pd.read_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights.csv", usecols=["Index", "DayofMonth", "DepTime", "ArrTime", "AirTime", "Distance", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay", "ArrDelay"])
delayed_f[:10]

,Index,DayofMonth,DepTime,ArrTime,AirTime,ArrDelay,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,3,2003.0,2211.0,116.0,-14.0,810,NaN,NaN,NaN,NaN,NaN
1,1,3,754.0,1002.0,113.0,2.0,810,NaN,NaN,NaN,NaN,NaN
2,2,3,628.0,804.0,76.0,14.0,515,NaN,NaN,NaN,NaN,NaN
3,4,3,1829.0,1959.0,77.0,34.0,515,2.0,0.0,0.0,0.0,32.0
4,5,3,1940.0,2121.0,87.0,11.0,688,NaN,NaN,NaN,NaN,NaN
5,6,3,1937.0,2037.0,230.0,57.0,1591,10.0,0.0,0.0,0.0,47.0
6,10,3,706.0,916.0,106.0,1.0,828,NaN,NaN,NaN,NaN,NaN
7,11,3,1644.0,1845.0,107.0,80.0,828,8.0,0.0,0.0,0.0,72.0
8,15,3,1029.0,1021.0,37.0,11.0,162,NaN,NaN,NaN,NaN,NaN
9,16,3,1452.0,1640.0,213.0,15.0,1489,3.0,0.0,0.0,0.0,12.0

In [40]:
delayed_f.set_index('Index')

,DayofMonth,DepTime,ArrTime,AirTime,ArrDelay,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Index,,,,,,,,,,,
0,3,2003.0,2211.0,116.0,-14.0,810,NaN,NaN,NaN,NaN,NaN
1,3,754.0,1002.0,113.0,2.0,810,NaN,NaN,NaN,NaN,NaN
2,3,628.0,804.0,76.0,14.0,515,NaN,NaN,NaN,NaN,NaN
4,3,1829.0,1959.0,77.0,34.0,515,2.0,0.0,0.0,0.0,32.0
5,3,1940.0,2121.0,87.0,11.0,688,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3505042,19,1551.0,1923.0,127.0,8.0,984,NaN,NaN,NaN,NaN,NaN
3505043,20,1555.0,1927.0,132.0,12.0,984,NaN,NaN,NaN,NaN,NaN
3505044,21,1555.0,1917.0,124.0,2.0,984,NaN,NaN,NaN,NaN,NaN
3505045,22,1607.0,1941.0,137.0,26.0,984,1.0,0.0,0.0,0.0,25.0
3505046,23,1608.0,1933.0,129.0,18.0,984,18.0,0.0,0.0,0.0,0.0

# Exercici 2

Fes un informe complet del data set:

- Resumeix estadÃ­sticament les columnes dâ€™interÃ¨s

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

delayed_f = pd.read_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights.csv", usecols=["Index", "Year", "Month", "DayofMonth", "DepTime", "ArrTime", "AirTime", "Distance", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay", "ArrDelay"])
delayed_f[:10]
delayed_f.describe()

,Index,Year,Month,DayofMonth,DepTime,ArrTime,AirTime,ArrDelay,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.048575e+06,1048575.0,1.048575e+06,1.048575e+06,1.048575e+06,1.044679e+06,1.044679e+06,1.044679e+06,1.048575e+06,685734.000000,685734.000000,685734.000000,685734.000000,685734.000000
mean,1.711115e+06,2008.0,3.385121e+00,1.542589e+01,1.519864e+03,1.610743e+03,1.070250e+02,4.218257e+01,7.513267e+02,18.870359,3.568032,14.429618,0.093284,25.334310
std,1.022871e+06,0.0,1.700650e+00,8.852621e+00,4.500644e+02,5.472327e+02,6.747848e+01,5.577485e+01,5.609676e+02,43.288445,20.724642,32.782977,1.999546,41.188379
min,0.000000e+00,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-6.900000e+01,1.100000e+01,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.343875e+05,2008.0,2.000000e+00,8.000000e+00,1.203000e+03,1.316000e+03,5.800000e+01,9.000000e+00,3.370000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.645956e+06,2008.0,3.000000e+00,1.500000e+01,1.546000e+03,1.715000e+03,8.900000e+01,2.500000e+01,6.020000e+02,2.000000,0.000000,2.000000,0.000000,9.000000
75%,2.606450e+06,2008.0,5.000000e+00,2.300000e+01,1.902000e+03,2.031000e+03,1.360000e+02,5.600000e+01,9.870000e+02,21.000000,0.000000,14.000000,0.000000,34.000000
max,3.505046e+06,2008.0,6.000000e+00,3.100000e+01,2.400000e+03,2.400000e+03,6.640000e+02,2.461000e+03,4.962000e+03,2436.000000,1148.000000,1357.000000,392.000000,1254.000000

- Troba quantes dades faltants hi ha per columna

In [42]:
delayed_f.isnull().sum(axis=0)

Index                     0
Year                      0
Month                     0
DayofMonth                0
DepTime                   0
ArrTime                3896
AirTime                3896
ArrDelay               3896
Distance                  0
CarrierDelay         362841
WeatherDelay         362841
NASDelay             362841
SecurityDelay        362841
LateAircraftDelay    362841
dtype: int64

- Crea columnes noves (velocitat mitjana del vol)

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

delayed_f = pd.read_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights.csv", usecols=["Index", "Year", "Month", "DayofMonth", "DepTime", "ArrTime", "AirTime", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay", "Distance"])
delayed_f[:10]

delayed_f["AverageSpeedFlight"] = round(delayed_f1['Distance']/(delayed_f1['AirTime']/60),0)
delayed_f[["Index", "Year", "Month", "DayofMonth", "DepTime", "ArrTime", "AirTime", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay", "Distance", "AverageSpeedFlight"]]

,Index,Year,Month,DayofMonth,DepTime,ArrTime,AirTime,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Distance,AverageSpeedFlight
0,0,2008,1,3,2003.0,2211.0,116.0,NaN,NaN,NaN,NaN,NaN,810,419.0
1,1,2008,1,3,754.0,1002.0,113.0,NaN,NaN,NaN,NaN,NaN,810,430.0
2,2,2008,1,3,628.0,804.0,76.0,NaN,NaN,NaN,NaN,NaN,515,407.0
3,4,2008,1,3,1829.0,1959.0,77.0,2.0,0.0,0.0,0.0,32.0,515,401.0
4,5,2008,1,3,1940.0,2121.0,87.0,NaN,NaN,NaN,NaN,NaN,688,474.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3505042,2008,6,19,1551.0,1923.0,127.0,NaN,NaN,NaN,NaN,NaN,984,465.0
1048571,3505043,2008,6,20,1555.0,1927.0,132.0,NaN,NaN,NaN,NaN,NaN,984,447.0
1048572,3505044,2008,6,21,1555.0,1917.0,124.0,NaN,NaN,NaN,NaN,NaN,984,476.0
1048573,3505045,2008,6,22,1607.0,1941.0,137.0,1.0,0.0,0.0,0.0,25.0,984,431.0
1048574,3505046,2008,6,23,1608.0,1933.0,129.0,18.0,0.0,0.0,0.0,0.0,984,458.0

- Crea columnes noves (si ha arribat tard o no)

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

delayed_f = pd.read_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights.csv", usecols=["Index", "Year", "Month", "DayofMonth", "DepTime", "ArrTime", "AirTime", "Distance", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay", "ArrDelay"])
delayed_f[:50]

delayed_f["AverageSpeedFlight"] = round(delayed_f['Distance']/(delayed_f['AirTime']/60),0)
delayed_f["Late Flight?"] = delayed_f["ArrDelay"].apply(lambda x: "Late" if x>0 else "On time")
delayed_f[["Index", "Year", "Month", "DayofMonth", "DepTime", "ArrTime", "AirTime", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay", "Distance", "AverageSpeedFlight", "ArrDelay", "Late Flight?"]]
delayed_f[:10]

,Index,Year,Month,DayofMonth,DepTime,ArrTime,AirTime,ArrDelay,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,AverageSpeedFlight,Late Flight?
0,0,2008,1,3,2003.0,2211.0,116.0,-14.0,810,NaN,NaN,NaN,NaN,NaN,419.0,On time
1,1,2008,1,3,754.0,1002.0,113.0,2.0,810,NaN,NaN,NaN,NaN,NaN,430.0,Late
2,2,2008,1,3,628.0,804.0,76.0,14.0,515,NaN,NaN,NaN,NaN,NaN,407.0,Late
3,4,2008,1,3,1829.0,1959.0,77.0,34.0,515,2.0,0.0,0.0,0.0,32.0,401.0,Late
4,5,2008,1,3,1940.0,2121.0,87.0,11.0,688,NaN,NaN,NaN,NaN,NaN,474.0,Late
5,6,2008,1,3,1937.0,2037.0,230.0,57.0,1591,10.0,0.0,0.0,0.0,47.0,415.0,Late
6,10,2008,1,3,706.0,916.0,106.0,1.0,828,NaN,NaN,NaN,NaN,NaN,469.0,Late
7,11,2008,1,3,1644.0,1845.0,107.0,80.0,828,8.0,0.0,0.0,0.0,72.0,464.0,Late
8,15,2008,1,3,1029.0,1021.0,37.0,11.0,162,NaN,NaN,NaN,NaN,NaN,263.0,Late
9,16,2008,1,3,1452.0,1640.0,213.0,15.0,1489,3.0,0.0,0.0,0.0,12.0,419.0,Late

- Taula de les aerolÃ­nies amb mÃ©s endarreriments acumulats

In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
delayed_f = pd.read_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights.csv") 


delayed_f["AccumulatedDelays"] = round(delayed_f["DepDelay"]+delayed_f["CarrierDelay"]+delayed_f["ArrDelay"]+delayed_f["WeatherDelay"]+delayed_f["SecurityDelay"]+delayed_f["NASDelay"]+delayed_f["LateAircraftDelay"])
delayed_f_group = delayed_f.groupby(["UniqueCarrier"]).agg({"AccumulatedDelays": np.median})
delayed_f_group.sort_values(by="AccumulatedDelays", ascending=False)[0:50]

               AccumulatedDelays
UniqueCarrier
YV                         155.0
B6                         150.0
UA                         146.0
XE                         139.0
AA                         136.0
9E                         136.0
MQ                         133.0
OO                         132.0
OH                         130.0
CO                         128.0
EV                         127.0
FL                         121.0
US                         119.0
NW                         114.0
AS                         114.0
DL                         112.0
WN                         107.0
AQ                          89.0
HA                          87.0
F9                          83.0

- Quins sÃ³n els vols mÃ©s llargs? I els mÃ©s endarrerits?

In [113]:
delayed_f["FlightNum"].describe()

delayed_f_longer = delayed_f.groupby(["FlightNum"]).agg({'Distance': np.median})
delayed_f_longer.sort_values(by="Distance", ascending=False)[0:30]

           Distance
FlightNum
14           2401.0
73           2398.0
845          2381.0
220          2300.0
784          2296.0
1899         2289.5
967          2288.0
2596         2279.0
272          2217.0
1829         2176.0
1802         2116.0
2066         2072.0
2073         2072.0
1193         2036.0
3379         2027.0
83           1999.0
2057         1999.0
181          1972.0
937          1946.0
885          1946.0
946          1946.0
267          1874.0
2078         1846.0
737          1846.0
155          1846.0
870          1846.0
1613         1846.0
1835         1846.0
1324         1797.0
173          1750.0

In [114]:
delayed_f_later = delayed_f.groupby(["FlightNum"]).agg({'DepDelay': np.median})
delayed_f_later.sort_values(by="DepDelay", ascending=False)[0:30]

           DepDelay
FlightNum
7487          350.0
7405          247.0
3548          217.0
6070          171.0
7450          155.0
9740          154.5
6228          153.0
6797          151.5
6697          151.0
4976          145.0
7389          144.0
7426          138.5
6779          135.0
7711          133.0
6846          133.0
7478          132.5
4997          130.0
4992          130.0
7437          129.0
6460          127.0
7363          126.5
7361          126.0
6258          120.0
7376          116.0
7489          114.5
7030          114.5
7029          111.5
3525          111.0
7759          110.0
4946          110.0

# Exercici 3

In [3]:
delayed_f.to_csv("C:/Users/ANA MARIA/Downloads/DelayedFlights_Clean.csv")